apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: data-engineering.cognira
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 8080
{{/* Nginx controller needs to be installed in the cluster: https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-helm/  */}}