apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  type: NodePort
  ports:
    - port: 8080
      targetPort: {{ .Values.configMap.PORT }}
      nodePort: 30002
      protocol: TCP